### ISSUE TITLE
Contact organisatie optie toevoegen aan central viewer

### ISSUE THREAD

**Issue by kad-floriw** [kadaster-labs/sensrnet-central-viewer#12]
Als gebruiker kan ik in de viewer op een sensor klikken en dan zie ik de (public) contact details en kan ik die gebruiken om contact op te nemen

**Comment by kad-bloemy** [comment]
Dit is nog niet geheel uitgekristalliseerd in het datamodel. Issue is nu of elke rol eigen contactgegevens moet kunnen beheren.

**Comment by kad-bloemy** [comment]
Vooralsnog gebruiken wij voor het MVP alleen de openbare (public) contactgegevens. De rol is opgenomen bij de contactgegevens.

**Comment by marcvanandel** [comment]
Dit moet nog wel gerealiseerd worden
