### ISSUE TITLE
Infopagina toevoegen

### ISSUE THREAD

**Issue by kad-busses** [kadaster-labs/sensrnet-central-viewer#3]
Een pagina met uitleg toevoegen waarop burgers etc. kunnen lezen wat SensRNet is, wat ze op de kaart kunnen zien en waar ze met vragen terecht kunnen.

**Comment by marcvanandel** [comment]
Is dit anders of juist hetzelfde als https://github.com/kadaster-labs/sensrnet-home/issues/64 ?

**Comment by kad-busses** [comment]
Zelfde, kan daar dus worden opgepakt. Deze kan worden gesloten 🙂
