### ISSUE TITLE
Observatiedoelen netjes tonen in centrale viewer

### ISSUE THREAD

**Issue by kad-floriw** [kadaster-labs/sensrnet-central-viewer#48]
Observatiedoelen worden nog niet goed weergegeven in de centrale viewer (zie https://github.com/kadaster-labs/sensrnet-home/discussions/271). Dit moet qua visualisatie netjes gemaakt worden, mogelijk gelijk aan de normale viewer.

**Comment by kad-bloemy** [comment]
In de registratietool kan ik bij Datastroom observatiedoel eindeloos intypen, waarbij het de tekst naar links schuift. Als ik niet toevallig begin met een letter van een bestaand observatiedoel krijg ik die ook niet te zien.

**Comment by marcvanandel** [comment]
Dat is een ander issue, @kad-bloemy. Ik dacht dat daar al een issue voor bestond ... maar dat kan ik niet vinden. Mocht dat er echt niet zijn, wil je dan een nieuw issue opvoeren? Dat is namelijk geen issue van de [central-viewer](https://github.com/kadaster-labs/sensrnet-central-viewer), maar van de [registry-frontend](https://github.com/kadaster-labs/sensrnet-registry-frontend) 😉
